######################################################################
# Automatically generated by qmake (3.0) ?? 6? 14 18:13:52 2019
######################################################################

TEMPLATE = app
TARGET = caclulator
INCLUDEPATH += .

# Input
HEADERS += expr.h model.h
FORMS += expr.ui
SOURCES += expr.cpp main.cpp model.cpp
